# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/trusty64"
  # config.vm.box = "hashicorp/precise64"

  # web is for installing apache
  config.vm.define "web" do |web|
    web.vm.network "forwarded_port", guest: 80, host: 8060
    web.vm.provision :shell, path: "provision.sh"
    # old syntax -> web.vm.network :hostonly, "192.168.33.10"
    web.vm.network :private_network, ip: "192.168.33.10"
  end

  # db is for intsalling mysql on another server
  config.vm.define "db" do |db|
    db.vm.provision :shell, path: "db_provision.sh"
    db.vm.network :private_network, ip: "192.168.33.11"
  end

end
